spring:
  profiles:
    active: dev
  config:
    import: "application-secrets-prod.yml"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
domain:
  address: http://localhost:8080
target:
  address: http://localhost:3000
file:
  upload-dir: src/main/resources/static/images
  location: c:\images



