spring:
  datasource:
    url: jdbc:mysql://<your-mysql-host>:<port>/<your-database-name> # aws profile 예정
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: <your-username>
    password: <your-password>
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100