spring:
  config:
    import: application-secrets-prod.yml
  datasource:
    url: jdbc:mysql://localhost:3306/changzipup
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: changzipup
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
 # naver oauth2 설정
 # 반드시 외부파일로 분리
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: tAF0P4jRzJskU8H5YXyd
            client-secret: NA_eLGOw0n
            authorization-grant-type: authorization_code #
            scope: name, email, nickname, gender, mobile
            redirect-uri: http://localhost:8080/api/members/oauth/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 로그인 인증 요청 url
            token-uri: https://nid.naver.com/oauth2.0/token # OAuth client가 제공하는 token 제공 uri
            user-name-attribute: response # oauth 2 인증 요청에 대한 응답이 response 라는 json에 담겨서 전송된다.
            user-info-uri: https://openapi.naver.com/v1/nid/me

  # kakao oauth2 설정
  # 반드시 외부파일로 분리

