spring:
  datasource:
    url: jdbc:mysql://localhost:3306/changzipup
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: changzipup
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

domain:
  address: http://localhost:8080
target:
  address: http://localhost:3000

file:
  upload-dir: src/main/resources/static/images
  location: c:\images

